/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sentry-debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trigger Error */
        get: operations["trigger_error_api_v1_sentry_debug_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Packages
         * @description List all packages (top-level groupings of survey collections).
         */
        get: operations["list_packages_api_v1_packages_get"];
        put?: never;
        /**
         * Create Package
         * @description Create a new package.
         */
        post: operations["create_package_api_v1_packages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packages/{package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Package
         * @description Get a package with its collections.
         */
        get: operations["get_package_api_v1_packages__package_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scope
         * @description Get the full data hierarchy: packages → collections → datasets with field metadata.
         */
        get: operations["get_scope_api_v1_scope_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Collection
         * @description Create a new collection within a package.
         */
        post: operations["create_collection_api_v1_collections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Collection
         * @description Get a collection with all its datasets.
         */
        get: operations["get_collection_api_v1_collections__collection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/consistency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Collection Consistency
         * @description List field inconsistencies across datasets in a collection (e.g. mismatched types or labels).
         */
        get: operations["get_collection_consistency_api_v1_collections__collection_id__consistency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description List datasets, optionally filtered by collection_id.
         */
        get: operations["list_datasets_api_v1_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset
         * @description Get a dataset with all its fields and metadata.
         */
        get: operations["get_dataset_api_v1_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset Responses
         * @description Get paginated raw survey responses for a dataset.
         */
        get: operations["get_dataset_responses_api_v1_datasets__dataset_id__responses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/field-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Field Tree
         * @description Get the hierarchical field tree for a dataset (groups and fields for use in query builder).
         */
        get: operations["get_field_tree_api_v1_datasets__dataset_id__field_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/weight-fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weight Fields
         * @description Get the numeric fields available as weighting variables for a dataset.
         */
        get: operations["get_weight_fields_api_v1_datasets__dataset_id__weight_fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Dataset Csv
         * @description Stream all responses for a dataset as a CSV file.
         */
        get: operations["download_dataset_csv_api_v1_datasets__dataset_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/crosstab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Crosstab
         * @description Run a cross-tabulation: rows × columns × optional breakdown, with optional weighting.
         */
        post: operations["run_crosstab_api_v1_analytics_crosstab_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Trend
         * @description Run a trend analysis: track a field's distribution across datasets in a collection over time.
         */
        post: operations["run_trend_api_v1_analytics_trend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Upload Sessions
         * @description List all non-committed, non-abandoned upload sessions (drafts).
         */
        get: operations["list_upload_sessions_api_v1_uploads_get"];
        put?: never;
        /** Create Upload */
        post: operations["create_upload_api_v1_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Upload Session */
        get: operations["get_upload_session_api_v1_uploads__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Discard Upload Session
         * @description Mark an upload session as abandoned (soft delete).
         */
        delete: operations["discard_upload_session_api_v1_uploads__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/fields/{field_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Override Field */
        patch: operations["override_field_api_v1_uploads__session_id__fields__field_id__patch"];
        trace?: never;
    };
    "/api/v1/uploads/{upload_session_id}/fields/{field_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Field */
        delete: operations["delete_field_api_v1_uploads__upload_session_id__fields__field_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reconcile Rows */
        get: operations["list_reconcile_rows_api_v1_uploads__session_id__reconcile_get"];
        put?: never;
        /** Trigger Reconcile */
        post: operations["trigger_reconcile_api_v1_uploads__session_id__reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/reconcile/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reconcile Ids */
        get: operations["get_reconcile_ids_api_v1_uploads__session_id__reconcile_ids_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/reconcile/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reconcile Counts */
        get: operations["get_reconcile_counts_api_v1_uploads__session_id__reconcile_counts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/suggested-reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suggested Reference */
        get: operations["get_suggested_reference_api_v1_uploads__session_id__suggested_reference_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/reconcile/{row_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Resolve Reconcile Row */
        patch: operations["resolve_reconcile_row_api_v1_uploads__session_id__reconcile__row_id__patch"];
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/reconcile/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Resolve Rows */
        post: operations["bulk_resolve_rows_api_v1_uploads__session_id__reconcile_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Upload Session */
        post: operations["commit_upload_session_api_v1_uploads__session_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/field-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Field Tree */
        get: operations["get_field_tree_api_v1_uploads__session_id__field_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/fieldgroups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Fieldgroup */
        post: operations["create_fieldgroup_api_v1_uploads__session_id__fieldgroups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/fieldgroups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Fieldgroup */
        delete: operations["delete_fieldgroup_api_v1_uploads__session_id__fieldgroups__group_id__delete"];
        options?: never;
        head?: never;
        /** Update Fieldgroup */
        patch: operations["update_fieldgroup_api_v1_uploads__session_id__fieldgroups__group_id__patch"];
        trace?: never;
    };
    "/api/v1/uploads/{upload_session_id}/fields/{field_id}/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert Level Route */
        put: operations["upsert_level_route_api_v1_uploads__upload_session_id__fields__field_id__levels_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{upload_session_id}/fields/{field_id}/levels/{level_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Level Route */
        delete: operations["delete_level_route_api_v1_uploads__upload_session_id__fields__field_id__levels__level_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{session_id}/fields/{field_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Move Field */
        patch: operations["move_field_api_v1_uploads__session_id__fields__field_id__move_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_upload_api_v1_uploads_post */
        Body_create_upload_api_v1_uploads_post: {
            /** File */
            file: string;
            /** Dataset Name */
            dataset_name: string;
            /** Collection Id */
            collection_id?: number | null;
            /** Collected At */
            collected_at?: string | null;
        };
        /** BulkResolve */
        BulkResolve: {
            /** Ids */
            ids: number[];
            action: components["schemas"]["ReconciliationStatus"];
        };
        /** CollectionCreate */
        CollectionCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Collection Type
             * @default generic
             */
            collection_type: string;
            /** Package Id */
            package_id: number;
        };
        /** CollectionRead */
        CollectionRead: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** @default generic */
            collection_type: components["schemas"]["CollectionType"];
            /** Package Id */
            package_id: number;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CollectionSummary */
        CollectionSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            collection_type: components["schemas"]["CollectionType"];
        };
        /**
         * CollectionType
         * @enum {string}
         */
        CollectionType: "survey" | "market_report" | "demographics" | "generic";
        /** CollectionWithDatasets */
        CollectionWithDatasets: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** @default generic */
            collection_type: components["schemas"]["CollectionType"];
            /** Package Id */
            package_id: number;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Datasets
             * @default []
             */
            datasets: components["schemas"]["DatasetSummary"][];
        };
        /** CrosstabMeta */
        CrosstabMeta: {
            /**
             * Mode
             * @default crosstab
             */
            mode: string;
            /** Row Fields */
            row_fields: components["schemas"]["MetaField"][];
            /** Col Fields */
            col_fields: components["schemas"]["MetaField"][];
            /** Row Mode */
            row_mode: string;
            /** Col Mode */
            col_mode: string;
            measure: components["schemas"]["MeasureSpec"];
            /** Dataset Name */
            dataset_name: string;
            /** Base N */
            base_n: number;
            /**
             * Level Labels
             * @default {}
             */
            level_labels: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /** CrosstabRequest */
        CrosstabRequest: {
            /** Dataset Id */
            dataset_id: number;
            /** Rows */
            rows: components["schemas"]["FieldSelection"][];
            /**
             * Row Mode
             * @default stacked
             * @enum {string}
             */
            row_mode: "stacked" | "nested";
            /**
             * Columns
             * @default []
             */
            columns: components["schemas"]["FieldSelection"][];
            /**
             * Col Mode
             * @default stacked
             * @enum {string}
             */
            col_mode: "stacked" | "nested";
            /**
             * Filters
             * @default []
             */
            filters: components["schemas"]["FilterSpec"][];
            measure: components["schemas"]["MeasureSpec"];
        };
        /** CrosstabResponse */
        CrosstabResponse: {
            meta: components["schemas"]["CrosstabMeta"];
            /** Rows */
            rows: components["schemas"]["ResultRow"][];
        };
        /** DatasetSummary */
        DatasetSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
            worker_type: components["schemas"]["WorkerType"];
        };
        /** DatasetWithFields */
        DatasetWithFields: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /** Collected At */
            collected_at?: string | null;
            /** @default jsonb_response */
            worker_type: components["schemas"]["WorkerType"];
            /** Collection Id */
            collection_id: number;
            /** Id */
            id: number;
            /** Worker Config */
            worker_config?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["FieldWithLevels"][];
        };
        /** FieldGroupCreate */
        FieldGroupCreate: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** FieldGroupUpdate */
        FieldGroupUpdate: {
            /** Name */
            name?: string | null;
            /** Parent Id */
            parent_id?: number | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** FieldMove */
        FieldMove: {
            /** Upload Fieldgroup Id */
            upload_fieldgroup_id: number | null;
        };
        /** FieldOut */
        FieldOut: {
            /** Id */
            id: number;
            /** Field Key */
            field_key: string;
            /** Display Name */
            display_name: string;
            field_type: components["schemas"]["FieldType"];
            /** Sort Order */
            sort_order: number;
            /** Is Filterable */
            is_filterable: boolean;
        };
        /** FieldOverride */
        FieldOverride: {
            override_type?: components["schemas"]["FieldType"] | null;
            /** Display Name */
            display_name?: string | null;
            /** Upload Fieldgroup Id */
            upload_fieldgroup_id?: number | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** FieldSelection */
        FieldSelection: {
            /** Field Key */
            field_key: string;
        };
        /** FieldTreeFieldOut */
        FieldTreeFieldOut: {
            /** Id */
            id: number;
            /** Field Key */
            field_key: string;
            /** Display Name */
            display_name: string;
            field_type: components["schemas"]["FieldType"];
            /** Sort Order */
            sort_order: number;
            /** Is Filterable */
            is_filterable: boolean;
        };
        /** FieldTreeGroupOut */
        FieldTreeGroupOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["FieldTreeFieldOut"][];
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["FieldTreeGroupOut"][];
        };
        /** FieldTreeOut */
        FieldTreeOut: {
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["FieldTreeGroupOut"][];
            /**
             * Ungrouped Fields
             * @default []
             */
            ungrouped_fields: components["schemas"]["FieldTreeFieldOut"][];
        };
        /**
         * FieldType
         * @enum {string}
         */
        FieldType: "numeric" | "ordinal" | "categorical" | "multi_response" | "identifier" | "weight";
        /** FieldWithLevels */
        FieldWithLevels: {
            /** Id */
            id: number;
            /** Field Key */
            field_key: string;
            /** Display Name */
            display_name: string;
            field_type: components["schemas"]["FieldType"];
            /** Sort Order */
            sort_order: number;
            /** Is Filterable */
            is_filterable: boolean;
            /**
             * Levels
             * @default []
             */
            levels: components["schemas"]["LevelOut"][];
        };
        /** FilterSpec */
        FilterSpec: {
            /** Field Key */
            field_key: string;
            /** Levels */
            levels?: string[] | null;
            /** Value Range */
            value_range?: [
                number,
                number
            ] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InconsistencyOut */
        InconsistencyOut: {
            /** Field Key */
            field_key: string;
            /** Inconsistency Type */
            inconsistency_type: string;
            /** Detail */
            detail: string;
        };
        /** LevelOut */
        LevelOut: {
            /** Id */
            id: number;
            /** Value */
            value: string;
            /** Display Label */
            display_label: string;
            /** Sort Order */
            sort_order: number;
        };
        /** LevelUpsert */
        LevelUpsert: {
            /** Raw Value */
            raw_value: string;
            /** Display Label */
            display_label?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /**
             * Is Inherited
             * @default false
             */
            is_inherited: boolean;
        };
        /** MeasureSpec */
        MeasureSpec: {
            /**
             * Type
             * @enum {string}
             */
            type: "count" | "weighted" | "value_field";
            /** Field Key */
            field_key?: string | null;
            /** Aggregation */
            aggregation?: ("sum" | "mean") | null;
            /**
             * Display
             * @default n
             * @enum {string}
             */
            display: "pct_col" | "pct_row" | "n";
        };
        /** MetaField */
        MetaField: {
            /** Field Key */
            field_key: string;
            /** Display Name */
            display_name: string;
        };
        /** PackageCreate */
        PackageCreate: {
            /** Name */
            name: string;
            /** Slug */
            slug?: string | null;
            /** Description */
            description?: string | null;
        };
        /** PackageRead */
        PackageRead: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PackageWithCollections */
        PackageWithCollections: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Collections
             * @default []
             */
            collections: components["schemas"]["CollectionSummary"][];
        };
        /** ReconcileTrigger */
        ReconcileTrigger: {
            /** Reference Dataset Id */
            reference_dataset_id: number;
        };
        /**
         * ReconciliationGroup
         * @enum {string}
         */
        ReconciliationGroup: "exact" | "probable" | "new_only" | "old_only";
        /**
         * ReconciliationStatus
         * @enum {string}
         */
        ReconciliationStatus: "auto_accepted" | "pending" | "confirmed" | "rejected" | "excluded";
        /** ResponsePage */
        ResponsePage: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Items */
            items: components["schemas"]["ResponseRead"][];
        };
        /** ResponseRead */
        ResponseRead: {
            /** Dataset Id */
            dataset_id: number;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ResultRow */
        ResultRow: {
            /** Key */
            key: string[];
            /** Values */
            values: {
                [key: string]: number;
            };
        };
        /** RowResolve */
        RowResolve: {
            /** Ref Field Id */
            ref_field_id?: number | null;
            /** Upload Field Id */
            upload_field_id?: number | null;
            status: components["schemas"]["ReconciliationStatus"];
        };
        /** ScopeCollection */
        ScopeCollection: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Datasets
             * @default []
             */
            datasets: components["schemas"]["ScopeDataset"][];
        };
        /** ScopeDataset */
        ScopeDataset: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** ScopePackage */
        ScopePackage: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Collections
             * @default []
             */
            collections: components["schemas"]["ScopeCollection"][];
        };
        /** TrendMeta */
        TrendMeta: {
            /**
             * Mode
             * @default trend
             */
            mode: string;
            /** Fields */
            fields: components["schemas"]["MetaField"][];
            breakdown?: components["schemas"]["MetaField"] | null;
            measure: components["schemas"]["MeasureSpec"];
            /** Collection Name */
            collection_name: string;
            /** Base N */
            base_n?: number | null;
            /**
             * Level Labels
             * @default {}
             */
            level_labels: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /** TrendRequest */
        TrendRequest: {
            /** Collection Id */
            collection_id: number;
            /** Fields */
            fields: components["schemas"]["FieldSelection"][];
            breakdown?: components["schemas"]["FieldSelection"] | null;
            /**
             * Filters
             * @default []
             */
            filters: components["schemas"]["FilterSpec"][];
            measure: components["schemas"]["MeasureSpec"];
        };
        /** TrendResponse */
        TrendResponse: {
            meta: components["schemas"]["TrendMeta"];
            /** Rows */
            rows: components["schemas"]["ResultRow"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkerType
         * @enum {string}
         */
        WorkerType: "jsonb_response" | "external_table";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    trigger_error_api_v1_sentry_debug_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_packages_api_v1_packages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageRead"][];
                };
            };
        };
    };
    create_package_api_v1_packages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_package_api_v1_packages__package_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageWithCollections"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scope_api_v1_scope_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopePackage"][];
                };
            };
        };
    };
    create_collection_api_v1_collections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CollectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_api_v1_collections__collection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionWithDatasets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_consistency_api_v1_collections__collection_id__consistency_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InconsistencyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_v1_datasets_get: {
        parameters: {
            query?: {
                collection_id?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_api_v1_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetWithFields"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_responses_api_v1_datasets__dataset_id__responses_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_field_tree_api_v1_datasets__dataset_id__field_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldTreeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weight_fields_api_v1_datasets__dataset_id__weight_fields_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_dataset_csv_api_v1_datasets__dataset_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_crosstab_api_v1_analytics_crosstab_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrosstabRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrosstabResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_trend_api_v1_analytics_trend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_upload_sessions_api_v1_uploads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_upload_api_v1_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_upload_api_v1_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_session_api_v1_uploads__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_upload_session_api_v1_uploads__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_field_api_v1_uploads__session_id__fields__field_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
                field_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldOverride"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_field_api_v1_uploads__upload_session_id__fields__field_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_session_id: number;
                field_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reconcile_rows_api_v1_uploads__session_id__reconcile_get: {
        parameters: {
            query?: {
                group?: components["schemas"]["ReconciliationGroup"] | null;
                after_id?: number | null;
                page_size?: number;
            };
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_reconcile_api_v1_uploads__session_id__reconcile_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconcileTrigger"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reconcile_ids_api_v1_uploads__session_id__reconcile_ids_get: {
        parameters: {
            query?: {
                group?: components["schemas"]["ReconciliationGroup"] | null;
            };
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reconcile_counts_api_v1_uploads__session_id__reconcile_counts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_suggested_reference_api_v1_uploads__session_id__suggested_reference_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_reconcile_row_api_v1_uploads__session_id__reconcile__row_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
                row_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RowResolve"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_resolve_rows_api_v1_uploads__session_id__reconcile_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkResolve"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_upload_session_api_v1_uploads__session_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_field_tree_api_v1_uploads__session_id__field_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_fieldgroup_api_v1_uploads__session_id__fieldgroups_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldGroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_fieldgroup_api_v1_uploads__session_id__fieldgroups__group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_fieldgroup_api_v1_uploads__session_id__fieldgroups__group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
                group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldGroupUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_level_route_api_v1_uploads__upload_session_id__fields__field_id__levels_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_session_id: number;
                field_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LevelUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_level_route_api_v1_uploads__upload_session_id__fields__field_id__levels__level_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_session_id: number;
                field_id: number;
                level_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_field_api_v1_uploads__session_id__fields__field_id__move_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
                field_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldMove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
