/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sentry-debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trigger Error */
        get: operations["trigger_error_api_v1_sentry_debug_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packages */
        get: operations["list_packages_api_v1_packages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packages/{package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Package */
        get: operations["get_package_api_v1_packages__package_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Collection */
        get: operations["get_collection_api_v1_collections__collection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collections/{collection_id}/consistency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Collection Consistency */
        get: operations["get_collection_consistency_api_v1_collections__collection_id__consistency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_api_v1_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Responses */
        get: operations["get_dataset_responses_api_v1_datasets__dataset_id__responses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/field-tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Field Tree */
        get: operations["get_field_tree_api_v1_datasets__dataset_id__field_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/weight-fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weight Fields */
        get: operations["get_weight_fields_api_v1_datasets__dataset_id__weight_fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/crosstab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Crosstab */
        post: operations["run_crosstab_api_v1_analytics_crosstab_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Trend */
        post: operations["run_trend_api_v1_analytics_trend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CollectionSummary */
        CollectionSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            collection_type: components["schemas"]["CollectionType"];
        };
        /**
         * CollectionType
         * @enum {string}
         */
        CollectionType: "survey" | "market_report" | "demographics" | "generic";
        /** CollectionWithDatasets */
        CollectionWithDatasets: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** @default generic */
            collection_type: components["schemas"]["CollectionType"];
            /** Package Id */
            package_id: number;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Datasets
             * @default []
             */
            datasets: components["schemas"]["DatasetSummary"][];
        };
        /** CrosstabMeta */
        CrosstabMeta: {
            /**
             * Mode
             * @default crosstab
             */
            mode: string;
            /** Row Fields */
            row_fields: components["schemas"]["MetaField"][];
            /** Col Fields */
            col_fields: components["schemas"]["MetaField"][];
            /** Row Mode */
            row_mode: string;
            /** Col Mode */
            col_mode: string;
            measure: components["schemas"]["MeasureSpec"];
            /** Dataset Name */
            dataset_name: string;
            /** Base N */
            base_n: number;
        };
        /** CrosstabRequest */
        CrosstabRequest: {
            /** Dataset Id */
            dataset_id: number;
            /** Rows */
            rows: components["schemas"]["FieldSelection"][];
            /**
             * Row Mode
             * @default stacked
             * @enum {string}
             */
            row_mode: "stacked" | "nested";
            /**
             * Columns
             * @default []
             */
            columns: components["schemas"]["FieldSelection"][];
            /**
             * Col Mode
             * @default stacked
             * @enum {string}
             */
            col_mode: "stacked" | "nested";
            /**
             * Filters
             * @default []
             */
            filters: components["schemas"]["FilterSpec"][];
            measure: components["schemas"]["MeasureSpec"];
        };
        /** CrosstabResponse */
        CrosstabResponse: {
            meta: components["schemas"]["CrosstabMeta"];
            /** Rows */
            rows: components["schemas"]["ResultRow"][];
        };
        /** DatasetSummary */
        DatasetSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Sort Order */
            sort_order: number;
            worker_type: components["schemas"]["WorkerType"];
        };
        /** DatasetWithFields */
        DatasetWithFields: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /** Collected At */
            collected_at?: string | null;
            /** @default jsonb_response */
            worker_type: components["schemas"]["WorkerType"];
            /** Collection Id */
            collection_id: number;
            /** Id */
            id: number;
            /** Worker Config */
            worker_config?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["FieldWithLevels"][];
        };
        /** FieldOut */
        FieldOut: {
            /** Id */
            id: number;
            /** Field Key */
            field_key: string;
            /** Display Name */
            display_name: string;
            field_type: components["schemas"]["FieldType"];
            /** Sort Order */
            sort_order: number;
            /** Is Filterable */
            is_filterable: boolean;
        };
        /** FieldSelection */
        FieldSelection: {
            /** Field Key */
            field_key: string;
        };
        /**
         * FieldType
         * @enum {string}
         */
        FieldType: "numeric" | "ordinal" | "categorical" | "multi_response" | "identifier" | "weight";
        /** FieldWithLevels */
        FieldWithLevels: {
            /** Id */
            id: number;
            /** Field Key */
            field_key: string;
            /** Display Name */
            display_name: string;
            field_type: components["schemas"]["FieldType"];
            /** Sort Order */
            sort_order: number;
            /** Is Filterable */
            is_filterable: boolean;
            /**
             * Levels
             * @default []
             */
            levels: components["schemas"]["LevelOut"][];
        };
        /** FilterSpec */
        FilterSpec: {
            /** Field Key */
            field_key: string;
            /** Levels */
            levels?: string[] | null;
            /** Value Range */
            value_range?: [
                number,
                number
            ] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InconsistencyOut */
        InconsistencyOut: {
            /** Field Key */
            field_key: string;
            /** Inconsistency Type */
            inconsistency_type: string;
            /** Detail */
            detail: string;
        };
        /** LevelOut */
        LevelOut: {
            /** Id */
            id: number;
            /** Value */
            value: string;
            /** Display Label */
            display_label: string;
            /** Sort Order */
            sort_order: number;
        };
        /** MeasureSpec */
        MeasureSpec: {
            /**
             * Type
             * @enum {string}
             */
            type: "count" | "weighted" | "value_field";
            /** Field Key */
            field_key?: string | null;
            /** Aggregation */
            aggregation?: ("sum" | "mean") | null;
            /**
             * Display
             * @default n
             * @enum {string}
             */
            display: "pct_col" | "pct_row" | "n";
        };
        /** MetaField */
        MetaField: {
            /** Field Key */
            field_key: string;
            /** Display Name */
            display_name: string;
        };
        /** PackageRead */
        PackageRead: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PackageWithCollections */
        PackageWithCollections: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Collections
             * @default []
             */
            collections: components["schemas"]["CollectionSummary"][];
        };
        /** ResponsePage */
        ResponsePage: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Items */
            items: components["schemas"]["ResponseRead"][];
        };
        /** ResponseRead */
        ResponseRead: {
            /** Dataset Id */
            dataset_id: number;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ResultRow */
        ResultRow: {
            /** Key */
            key: string[];
            /** Values */
            values: {
                [key: string]: number;
            };
        };
        /** TrendMeta */
        TrendMeta: {
            /**
             * Mode
             * @default trend
             */
            mode: string;
            /** Fields */
            fields: components["schemas"]["MetaField"][];
            breakdown?: components["schemas"]["MetaField"] | null;
            measure: components["schemas"]["MeasureSpec"];
            /** Collection Name */
            collection_name: string;
        };
        /** TrendRequest */
        TrendRequest: {
            /** Collection Id */
            collection_id: number;
            /** Fields */
            fields: components["schemas"]["FieldSelection"][];
            breakdown?: components["schemas"]["FieldSelection"] | null;
            /**
             * Filters
             * @default []
             */
            filters: components["schemas"]["FilterSpec"][];
            measure: components["schemas"]["MeasureSpec"];
        };
        /** TrendResponse */
        TrendResponse: {
            meta: components["schemas"]["TrendMeta"];
            /** Rows */
            rows: components["schemas"]["ResultRow"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkerType
         * @enum {string}
         */
        WorkerType: "jsonb_response" | "external_table";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    trigger_error_api_v1_sentry_debug_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_packages_api_v1_packages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageRead"][];
                };
            };
        };
    };
    get_package_api_v1_packages__package_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageWithCollections"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_api_v1_collections__collection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionWithDatasets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_collection_consistency_api_v1_collections__collection_id__consistency_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                collection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InconsistencyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_api_v1_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetWithFields"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_responses_api_v1_datasets__dataset_id__responses_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponsePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_field_tree_api_v1_datasets__dataset_id__field_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weight_fields_api_v1_datasets__dataset_id__weight_fields_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_crosstab_api_v1_analytics_crosstab_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrosstabRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrosstabResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_trend_api_v1_analytics_trend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
