"""add_analytics_schema

Revision ID: 169c1426e60c
Revises: af765d6836a8
Create Date: 2026-04-11 21:16:06.812720

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "169c1426e60c"
down_revision: str | None = "af765d6836a8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extend the fieldtype enum with new special field types
    op.execute("ALTER TYPE fieldtype ADD VALUE IF NOT EXISTS 'identifier'")
    op.execute("ALTER TYPE fieldtype ADD VALUE IF NOT EXISTS 'weight'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fieldgroup",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["fieldgroup.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("field", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_foreign_key("fk_field_group_id", "field", "fieldgroup", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_field_group_id", "field", type_="foreignkey")
    op.drop_column("field", "group_id")
    op.drop_table("fieldgroup")
    # ### end Alembic commands ###
