"""add_confidence_value_sample

Revision ID: 2c1e1c77846f
Revises: a09555137ea9
Create Date: 2026-04-17 13:44:51.332825

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "2c1e1c77846f"
down_revision: str | None = "a09555137ea9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "upload_field", sa.Column("confidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column(
        "upload_field",
        sa.Column("value_sample", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upload_field", "value_sample")
    op.drop_column("upload_field", "confidence")
    # ### end Alembic commands ###
