"""add_upload_level_is_inherited

Revision ID: 375fd7684c8b
Revises: 2c1e1c77846f
Create Date: 2026-04-17 18:04:26.077328

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "375fd7684c8b"
down_revision: str | None = "2c1e1c77846f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "upload_level",
        sa.Column("is_inherited", sa.Boolean(), server_default=sa.false(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upload_level", "is_inherited")
    # ### end Alembic commands ###
