"""add upload tables

Revision ID: a09555137ea9
Revises: 169c1426e60c
Create Date: 2026-04-17 09:53:39.943941

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a09555137ea9"
down_revision: str | None = "169c1426e60c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload_session",
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "detecting",
                "reconciling",
                "editing",
                "committed",
                "abandoned",
                name="uploadsessionstatus",
            ),
            nullable=False,
        ),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column("dataset_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("collected_at", sa.Date(), nullable=True),
        sa.Column("reference_dataset_id", sa.Integer(), nullable=True),
        sa.Column("committed_dataset_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["committed_dataset_id"],
            ["dataset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reference_dataset_id"],
            ["dataset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "upload_fieldgroup",
        sa.Column("upload_session_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["upload_fieldgroup.id"],
        ),
        sa.ForeignKeyConstraint(
            ["upload_session_id"],
            ["upload_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "upload_field",
        sa.Column("upload_session_id", sa.Integer(), nullable=False),
        sa.Column("field_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "detected_type",
            postgresql.ENUM(
                "numeric",
                "ordinal",
                "categorical",
                "multi_response",
                "identifier",
                "weight",
                name="fieldtype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "override_type",
            postgresql.ENUM(
                "numeric",
                "ordinal",
                "categorical",
                "multi_response",
                "identifier",
                "weight",
                name="fieldtype",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("upload_fieldgroup_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["upload_fieldgroup_id"],
            ["upload_fieldgroup.id"],
        ),
        sa.ForeignKeyConstraint(
            ["upload_session_id"],
            ["upload_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reconciliation_row",
        sa.Column("upload_session_id", sa.Integer(), nullable=False),
        sa.Column("upload_field_id", sa.Integer(), nullable=True),
        sa.Column("ref_field_id", sa.Integer(), nullable=True),
        sa.Column(
            "group",
            sa.Enum("exact", "probable", "new_only", "old_only", name="reconciliationgroup"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "auto_accepted",
                "pending",
                "confirmed",
                "rejected",
                "excluded",
                name="reconciliationstatus",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ref_field_id"],
            ["field.id"],
        ),
        sa.ForeignKeyConstraint(
            ["upload_field_id"],
            ["upload_field.id"],
        ),
        sa.ForeignKeyConstraint(
            ["upload_session_id"],
            ["upload_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "upload_level",
        sa.Column("upload_field_id", sa.Integer(), nullable=False),
        sa.Column("raw_value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["upload_field_id"],
            ["upload_field.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("upload_level")
    op.drop_table("reconciliation_row")
    op.drop_table("upload_field")
    op.drop_table("upload_fieldgroup")
    op.drop_table("upload_session")
    sa.Enum(name="reconciliationstatus").drop(op.get_bind())
    sa.Enum(name="reconciliationgroup").drop(op.get_bind())
    sa.Enum(name="uploadsessionstatus").drop(op.get_bind())
    # ### end Alembic commands ###
