class DomainError(Exception): ...


class PackageNotFoundError(DomainError): ...


class CollectionNotFoundError(DomainError): ...


class DatasetNotFoundError(DomainError): ...


class UploadSessionNotFoundError(DomainError): ...


class FieldNotFoundError(DomainError): ...


class FieldGroupNotFoundError(DomainError): ...


class LevelNotFoundError(DomainError): ...


class ReconciliationRowNotFoundError(DomainError): ...


class AIServiceError(DomainError): ...
