class DomainError(Exception): ...


class PackageNotFoundError(DomainError): ...


class CollectionNotFoundError(DomainError): ...


class DatasetNotFoundError(DomainError): ...


class UploadSessionNotFoundError(DomainError): ...


class UploadSessionConflictError(DomainError): ...
